sudo: false
language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "stable"

cache:
  yarn: true
  directories:
  - node_modules/

before_install:
  - npm i -g nyc codecov

after_success:
  - nyc report --reporter=lcov > coverage.lcov && codecov
